In [56]:
import pandas as pd

In [57]:
df = pd.read_csv('yelp_business.txt',sep='\t')
df

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,G5ERFWvPfHy7IDAUYlWL2A,All Colors Mobile Bumper Repair,NaN,7137 N 28th Ave,Phoenix,AZ,85051,33.45,-112.07,1.0,4,1,Auto Detailing;Automotive
1,0jDvRJS-z9zdMgOUXgr6rA,Sunfare,NaN,811 W Deer Valley Rd,Phoenix,AZ,85027,33.68,-112.08,5.0,27,1,Personal Chefs;Food;Gluten-Free;Food Delivery ...
2,6HmDqeNNZtHMK0t2glF_gg,Dry Clean Vegas,Southeast,"2550 Windmill Ln, Ste 100",Las Vegas,NV,89123,36.04,-115.12,1.0,4,1,Dry Cleaning & Laundry;Laundry Services;Local ...
3,pbt3SBcEmxCfZPdnmU9tNA,The Cuyahoga Room,NaN,740 Munroe Falls Ave,Cuyahoga Falls,OH,44221,41.14,-81.47,1.0,3,0,Wedding Planning;Caterers;Event Planning & Ser...
4,CX8pfLn7Bk9o2-8yDMp_2w,The UPS Store,NaN,"4815 E Carefree Hwy, Ste 108",Cave Creek,AZ,85331,33.80,-111.98,1.5,5,1,Notaries;Printing Services;Local Services;Ship...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,l4xrBZAKLXpSR4iprqTw8A,Mark's,NaN,"1015 Lakeshore Boulevard E, Unit 5",Toronto,ON,M4M 1B3,43.66,-79.33,5.0,3,1,Women's Clothing;Shopping;Fashion;Men's Clothing
96,ICdzSGuv70gpSk7aqpIrHw,Wok-In Bbq,NaN,"3540 Rutherford Road, Unit 67",Vaughan,ON,L4H 3T8,43.83,-79.55,4.5,10,1,Chinese;Barbeque;Restaurants
97,wk3wGDfJb1V-ciZpyhoNAA,Bic's Pub and Grill,NaN,560 State Road 130,Trafford,PA,15085,40.39,-79.73,4.5,7,1,Pubs;American (Traditional);Nightlife;Bars;Piz...
98,NBYN4Nks_EsPHyAlJ_mdNw,Bistro Merlot,NaN,18425 Antoine Faucon,Pierrefonds,QC,H9K 1M7,45.45,-73.89,4.5,8,0,Salad;Pizza;Restaurants;Event Planning & Servi...
99,xPy6fq53MdGMxtbvxBD4RA,The Addison,NaN,2674 N Park Ln,Fitchburg,WI,53711,43.00,-89.40,5.0,5,1,Property Management;Condominiums;Apartments;Ho...

In [58]:
df['rank']=df['review_count'].rank(method='first',ascending=False)

In [65]:
df=df.sort_values('rank').head(5)
results = df[['name','review_count']]
results

                         name  review_count
68                  Iron Chef           331
88  Jacs Dining and Tap House           197
63        Grimaldi's Pizzeria           187
84           Signs Restaurant           120
86                   Kassab's           101